//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Calculate1000DaysLibrary", ConfigurationName="ICalculateDaysClass")]
public interface ICalculateDaysClass
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Calculate1000DaysLibrary/ICalculateDaysClass/GetNextDateWhen1000", ReplyAction="http://Calculate1000DaysLibrary/ICalculateDaysClass/GetNextDateWhen1000Response")]
    System.DateTime GetNextDateWhen1000(string date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Calculate1000DaysLibrary/ICalculateDaysClass/GetNextDateWhen1000", ReplyAction="http://Calculate1000DaysLibrary/ICalculateDaysClass/GetNextDateWhen1000Response")]
    System.Threading.Tasks.Task<System.DateTime> GetNextDateWhen1000Async(string date);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculateDaysClassChannel : ICalculateDaysClass, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculateDaysClassClient : System.ServiceModel.ClientBase<ICalculateDaysClass>, ICalculateDaysClass
{
    
    public CalculateDaysClassClient()
    {
    }
    
    public CalculateDaysClassClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculateDaysClassClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateDaysClassClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateDaysClassClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.DateTime GetNextDateWhen1000(string date)
    {
        return base.Channel.GetNextDateWhen1000(date);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> GetNextDateWhen1000Async(string date)
    {
        return base.Channel.GetNextDateWhen1000Async(date);
    }
}
